version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    environment:
      POSTGRES_DB: 'db'           # Nombre de la base de datos
      POSTGRES_USER: 'user'       # Usuario de la base de datos
      POSTGRES_PASSWORD: '1234'   # Contraseña de la base de datos
      DB_HOST: 'db'               # El nombre del servicio de PostgreSQL en Docker
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/database:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
